### ISSUE TITLE
HU-01: Recepción de intenciones del usuario en lenguaje natural

### ISSUE THREAD

**Issue by frandanielar** [INF225-2023-2-P201/02-digicore#1]
-  **Descripción:** Como Administrador de Sistemas, quiero poder expresar mis intenciones/deseos en lenguaje natural para que el sistema las comprenda y procese.

-  **Condición de aceptación:** Dado un Administrador de Sistemas, cuando este ingrese sus intenciones en lenguaje natural, entonces el sistema las interpretará para procesarlas.

-  **Tareas:**
1. Definir estructura.
2. Implementar interfaz de entrada de texto.
3. Definir flujo de interacción con usuario.

- **Limitaciones:** Integración con el framework adhoc de la Capa Empresarial.

**Comment by floraciendo** [comment]
Se recepciona la intención del usuario con lo implementado de la app hasta el momento
